spring:
  application:
    name: backend

  datasource:
    url: ${EFUS_DB_URL}
    username: ${EFUS_DB_USERNAME}
    password: ${EFUS_DB_PASSWORD}
    driver-class-name: ${EFUS_DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${EFUS_JPA_DDL_AUTO:update}
    show-sql: ${EFUS_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${EFUS_JPA_FORMAT_SQL:true}

server:
  port: ${EFUS_SERVER_PORT:8080}


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/kakao/login}

jwt:
  secret: ${JWT_SECRET:EfusApplicationSuperSecretKeyForJwtTokenGeneration2026}

  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 1209600

cloud:
  aws:
    region: ${EFUS_AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${EFUS_S3_BUCKET}
    credentials:
      access-key: ${EFUS_AWS_ACCESS_KEY}
      secret-key: ${EFUS_AWS_SECRET_KEY}

